### ISSUE TITLE
Relative URL's won't open

### ISSUE THREAD

**Issue by mickn** [eliaskg/Hacky#12] opened 2013-03-23 10:31 UTC
When clicking on a relative URL (mostly 'Ask HN' topics), the URL will not open.
The website which is parsed does not provide a base URL for local pages.

Hacky should check if a base URL is given and otherwise add 'http://news.ycombinator.com/'.

**Comment by eliaskg** [comment] 2013-03-23 10:32
Thanks for your report! The issue is known and will be fixed in the upcoming update.

**Closed as completed by eliaskg** 2013-03-23 10:32 UTC

**Comment by mickn** [comment] 2013-03-23 10:41
Great!
I couldn't wait, so wrote a quick fix for myself. Maybe you can use it, if you haven't fixed it already.
53ec3cae0892e0d99dac1e3e0551820df6480ad0

**Comment by eliaskg** [comment] 2013-03-23 10:46
It's already fixed and waiting for review in the App Store.

![Soon](http://i2.kym-cdn.com/photos/images/original/000/117/021/enhanced-buzz-28895-1301694293-0.jpg)

**Comment by mickn** [comment] 2013-03-26 12:58
Are you planning to release the code of the new version on Github as well, or is this just for the App Store?

Thanks!

**Comment by eliaskg** [comment] 2013-03-26 13:09
Every update will be released on GitHub as soon as it is available in the Mac App Store.

**Comment by sjmulder** [comment] 2013-03-26 13:14
Hey @eliaskg, it’s fantastic that your willing to share your work like this. However, this policy does make it hard for people to contribute since you never know you might be doing duplicate work or will have to rework your code when the new release drops.

**Comment by eliaskg** [comment] 2013-03-26 18:00
@sjmulder Good point. I think about implementing a roadmap on GitHub so you guys know what I am currently working on.

**Comment by sjmulder** [comment] 2013-03-26 18:01
Thanks, that’ll help a lot!
